version: "3.0"
services:
  node:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: node:cpascher
    user: "node"
    working_dir: /Sites/CodePhoenixOrg/SDK/javascript/Cpascher
    environment:
      - NODE_ENV=production
    ports:
     - '3000:3000'
     - '5000:5000'
    volumes:
      - .:/Sites/CodePhoenixOrg/SDK/javascript/Cpascher
      - node_modules:/Sites/CodePhoenixOrg/SDK/javascript/Cpascher/node_modules
    command: /bin/sh -c "cd /Sites/CodePhoenixOrg/SDK/javascript/Cpascher; sudo yarn; yarn start; while sleep 1000; do :; done;"
volumes: 
  node_modules: 