version: "3.0"
services:
  node:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: node:recommerce
    user: "node"
    working_dir: /site
    environment:
      - NODE_ENV=production
    ports:
     - '3000:3000'
     - '5000:5000'
    volumes:
      - .:/site
      - node_modules:/site/node_modules
    command: /bin/sh -c "cd /site; sudo yarn; yarn start; while sleep 1000; do :; done;"
volumes: 
  node_modules:                                                                                                                                                                                                 